# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
common: &common
  adapter: postgresql
  encoding: utf8
  host: localhost
  username:
  password:
  pool: 8

development:
  <<: *common
  database: recipechecker_development

test:
  <<: *common
  database: recipechecker_test

production:
  <<: *common
  database: recipechecker_production
  username: postgres
  password: postgres

